### ISSUE TITLE
Install page error.

### ISSUE THREAD

**Issue by pdglobal** [derp-all-day/JSBot#1]
PHP Notice:  Undefined property: stdClass::$step in C:\PDGLOBAL.NET\htdocs\admin\install.php on line 11
PHP Notice:  Undefined property: stdClass::$step in C:\PDGLOBAL.NET\htdocs\admin\install.php on line 25

I'm running php 7 via fastcgi in IIS on windows server 2016.

**Comment by derp-all-day** [comment]
Can you put the code:
```echo '<pre>';
print_r($get);
die();```

After line 10 in the code, and run it and share the output?

**Comment by pdglobal** [comment]
stdClass Object
(
    [step] => 1
)

**Comment by pdglobal** [comment]
Nevermind I got it working, I just had to add error_reporting(0) before all the other code.

**Comment by derp-all-day** [comment]
I also found the bug. Just forgot to add die(); after the deader redirect at the top. Fixed, and glad you found your own solution. :) Hope you enjoy it, I'll close this now, however if you come across any other issues feel free to open another ticket, infact please do. :)
