### ISSUE TITLE
Confused about functionality

### ISSUE THREAD

**Issue by pdglobal** [derp-all-day/JSBot#2]
Does it not yet have all the functionality of the description?

When I get it working I just see this.

![image](https://user-images.githubusercontent.com/36902779/72236958-c984fa80-35a6-11ea-978a-ddf9f39353bd.png)

**Comment by derp-all-day** [comment]
Once you have a slave loaded in there, you will be displayed a list of slaves you have access to and can click on the slave you wish to manage and the options/functionalities will be there.

**Comment by derp-all-day** [comment]
It will look like this. When the slave is online the IP addr will show in green, and when offline the ip addr will show in red.

![Untitled](https://user-images.githubusercontent.com/17708635/72259558-690db180-35d6-11ea-932c-ef1848f03eb5.png)

**Comment by derp-all-day** [comment]
Even with no slaves it should still look like this (Youre missing a segment). This is brought in through ajax. Can you open your browser console and reload the page and share any errors the console is displaying to you?

![Untitled](https://user-images.githubusercontent.com/17708635/72260187-e685f180-35d7-11ea-98af-ed2bdd77fd22.png)

**Comment by pdglobal** [comment]
![image](https://user-images.githubusercontent.com/36902779/72279056-4e056680-3603-11ea-8cb4-6c788dbc56d0.png)

![image](https://user-images.githubusercontent.com/36902779/72279097-637a9080-3603-11ea-8d3c-1d92844fccd3.png)

**Comment by pdglobal** [comment]
The chart.js folder is not present in my vendor folder.

**Comment by pdglobal** [comment]
Also appears to be a syntax error in the ajax file and jquery file

**Comment by derp-all-day** [comment]
As far as the charts.js goes, you can just remove it from index.php or just coppy the updated version off here into index.php on your host.

as far as the error, if that doesnt fix it, click on the link in the cosole next to the error for ajax.php

I've highlighted in the attached image what you should click. And share with me the piece of code it displays to you (it will show you what piece of code if causing the issue).
![Untitled](https://user-images.githubusercontent.com/17708635/72280825-dc2b1e00-35fe-11ea-9de5-7383914bf8fc.png)

**Comment by derp-all-day** [comment]
Its showing that theres a '<' on line 1 when in fact there is not unless you added something there. But weirder things have happenned. It is all working fine on my end, so no worries. We'll get you sorted out. :)

**Comment by pdglobal** [comment]
Okay, I had to turn off a cgi handler called IIS Node. The js files were being interpreted as server side node script.

After this I'm able to see the additional segment of the website.

However when the website is loaded, with the server included, no users show up.

I added the following to my head
<script src="https://pdglobal.app/admin/js/listener.php" ></script>

What am I doing wrong?

**Comment by derp-all-day** [comment]
You have to have that page loaded and in view for it to register.

Also, to make sure nothing else is going on, open up dev tools and reload the page with the script included (Also it is best practice to add scripts in the footer rather than the header) and:
1. look for any console errors related to it and send that over.
and
2. check in the network portion to see if the xhr requests to your panel are being made from the server.

And send me your results here

**Comment by derp-all-day** [comment]
Okay I checked your site for you, seems to be working now. :)

Also, using the browser extension instead (If applicable to your needs) will always provide a more stable experience

**Comment by pdglobal** [comment]
If you look in the network log you will see it's trying to request https://pdglobal.app/://pdglobal.app/admin/portal.php?post=hello&cb=1273206

not https://pdglobal.app/admin/portal.php?post=hello&cb=1273206

**Comment by derp-all-day** [comment]
ALso icould try changing:
<script src="/admin/js/listener.php" ></script>

to:
<script src="https://pdglobal.app/admin/portal.php" ></script>

**Comment by pdglobal** [comment]
That was my original configuration. The error is something to do with how the ajax request is being made, when I change it to

**Comment by derp-all-day** [comment]
And yeah I'm seeing that. You have it in correct, I have no clue why its trying to request like that. My only guess is it's something to do with either IIS (Which I have very little expirience with), or security directives on your site.

Can you change it back to the https://? I'll give it a look from my end and see if I cant figure this one out.

**Comment by pdglobal** [comment]
Sure thing, it's done now.

**Comment by derp-all-day** [comment]
I think I figured it out, give me 1 sec and I'll explain.

**Comment by derp-all-day** [comment]
add: ?proto=https to the end of the url. Its something I added when I was working on the extensions bug forgot about changing in panel.

So your script tag should look like:
<script src="https://pdglobal.app/admin/portal.php?proto=https" ></script>

I'll update the source so that it reflects that need in the panel and will follow up with a reply here in a few of which files you should update.

**Comment by pdglobal** [comment]
I got it working.

**Comment by pdglobal** [comment]
I changed line 19 in listener.php to:

  host_url: "<?=str_replace('/js/listener.php', '', $_SERVER['PHP_SELF'])?>",

**Comment by derp-all-day** [comment]
That works too, but all you need to do is add the '?proto=https' to the end of the url in script tag.

Also, you can now update your index.php and it will reflect that requirement in the displayed server url.

Glad it working now though. :)

Anything else before we close this?

**Comment by pdglobal** [comment]
I'll open another ticket as it's off topic.
