### ISSUE TITLE
what is the file server.js

### ISSUE THREAD

**Issue by hakanonymos** [derp-all-day/JSBot#7]
hello i like your project but i have not found the file " server.js" for the extension

**Comment by hakanonymos** [comment]
thank you i have test your project it is good but there is a probleme with screenshot and i suggere that it will be very good to load directly keylogger

**Comment by derp-all-day** [comment]
The screenshot is just a mockup render of the current webview of the slave. The sever.js is linked in the panel (Generated upon going through the setup process).

**Comment by hakanonymos** [comment]
yes i have seen that thank you

**Comment by hakanonymos** [comment]
insert js file has probleme no file named " cmd.php " , i think it is the file " portal.php "

**Comment by derp-all-day** [comment]
Show a screenshot of the etror youre getting?

**Comment by derp-all-day** [comment]
*of the error

**Comment by derp-all-day** [comment]
Assuming you have resolved your issue.
